package ro.adventist.copiiiregelui.models


enum class BibleBookType : LocalizedString {
    genesis,
    exodus,
    leviticus,
    numbers,
    deuteronomy,
    joshua,
    judges,
    ruth,
    samuel1,
    samuel2,
    kings1,
    kings2,
    chronicals1,
    chronicals2,
    ezra,
    nehemiah,
    esther,
    job,
    psalms,
    proverbs,
    ecclesiastes,
    songOfSongs,
    isaiah,
    jeremiah,
    lamentations,
    ezekiel,
    daniel,
    hosea,
    joel,
    amos,
    obadiah,
    jonah,
    micah,
    nahum,
    habakkuk,
    zephanish,
    haggai,
    zechariah,
    malachi,
    matthew,
    mark,
    luke,
    john,
    actsOfTheApostles,
    romans,
    corinthians1,
    corinthians2,
    galatians,
    ephesians,
    philippians,
    colossians,
    thessalonians1,
    thessalonians2,
    timothy1,
    timothy2,
    titus,
    philemon,
    hebrews,
    james,
    peter1,
    peter2,
    john1,
    john2,
    john3,
    jude,
    revelation;

    companion object {
        fun getBibleBook(type: String): BibleBookType {
            return BibleBookType.values()
                .firstOrNull { bibleBookType -> bibleBookType.name == type }
                ?: BibleBookType.genesis
        }
    }
}