package ro.adventist.copiiiregelui.models

import ro.adventist.copiiiregelui.R
import ro.adventist.copiiiregelui.utils.GenericUtils

interface Labeled {
    val name: String
}

interface FirestoreCollection : Labeled {
}

interface LocalizedString : Labeled {

    fun getLocalizedString(): String {
        return GenericUtils.getStringByResourceIdentifier(name, name)
    }
}


enum class CategorySectionType(
    val titleRes: Int,
    val hintRes: Int = -1,
    val emptyRes: Int = -1,
    val addLabelRes: Int = -1,
    val editLabelRes: Int = -1,
    val deleteMessageRes: Int = -1,
    val modelClass: Class<out FirestoreModel> = BibleDiscovery::class.java) : FirestoreCollection {
    bibleDiscoveries(R.string.bibleDiscoveriesTitle,
        R.string.bibleDiscoveriesHint,
        R.string.noDiscoveriesMessage,
        R.string.addNewDiscovery,
        R.string.editDiscovery,
        R.string.deleteDiscoveryMessage,
        BibleDiscovery::class.java),
    bibleFavoriteTexts(R.string.bibleFavoriteTextsTitle,
        R.string.bibleFavoriteTextsHint,
        R.string.noFavoriteTextsMessage,
        R.string.addNewFavoriteText,
        R.string.editFavoriteText,
        R.string.deleteFavoriteTextMessage,
        BibleFavoriteText::class.java),
    biblePrayerTexts(R.string.biblePrayerTextsTitle,
        R.string.biblePrayerTextsHint,
        R.string.noPrayerTextsMessage,
        R.string.addNewPrayerText,
        R.string.editPrayerText,
        R.string.deletePrayerTextMessage,
        BiblePrayerText::class.java),
    prayerSubjects(R.string.prayerSubjectsTitle,
        R.string.prayerSubjectsHint,
        R.string.noPrayerSubjectsMessage,
        R.string.addNewPrayerSubject,
        R.string.editPrayerSubject,
        R.string.deletePrayerSubjectMessage,
        PrayerSubject::class.java),
    prayerPeople(R.string.prayerPeopleTitle,
        R.string.prayerPeopleHint,
        R.string.noPrayerPeopleMessage,
        R.string.addPrayerPeople,
        R.string.editPrayerPeople,
        R.string.deletePrayerPeopleMessage,
        PrayerPeople::class.java),
    bodyRoutines(R.string.bodyRoutinesTitle,
        R.string.bodyRoutinesHint,
        R.string.noBodyRoutinesMessage,
        R.string.addNewBodyRoutine,
        R.string.editBodyRoutine,
        R.string.deleteBodyRoutineMessage,
        BodyRoutine::class.java),
    healthMetrics(R.string.healthMetricsTitle,
        R.string.healthMetricsHint,
        R.string.noHealthMetricMessage,
        R.string.addNewHealthMetrics,
        R.string.editHealthMetrics,
        R.string.deleteHealthMetricsMessage,
        HealthMetric::class.java),
    healthDiscoveries(R.string.healthDiscoveriesTitle,
        R.string.healthDiscoveriesHint,
        R.string.noHealthDiscoveriesMessage,
        R.string.addNewHealthDiscovery,
        R.string.editHealthDiscovery,
        R.string.deleteHealthDiscoveryMessage,
        HealthDiscovery::class.java),
    sportPractice(R.string.sportPracticeTitle,
        R.string.sportPracticeHint,
        R.string.noSportPracticeMessage,
        R.string.addNewSportPractice,
        R.string.editSportPractice,
        R.string.deleteSportPracticeMessage,
        SportPractice::class.java),
    knowledgeFindings(R.string.knowledgeFindingsTitle,
        R.string.knowledgeFindingsHint,
        R.string.noFindingMessage,
        R.string.addNewFinding,
        R.string.editFinding,
        R.string.deleteFindingMessage,
        KnowledgeFinding::class.java),
    hobbies(R.string.hobbiesTitle,
        R.string.hobbiesHint,
        R.string.noHobbiesMessage,
        R.string.addNewHobby,
        R.string.editHobby,
        R.string.deleteHobbyMessage,
        HobbyItem::class.java),
    mediaDiscoveries(R.string.mediaDiscoveriesTitle,
        R.string.mediaDiscoveriesHint,
        R.string.noMediaDiscoveriesMessage,
        R.string.addNewMediaDiscovery,
        R.string.editMediaDiscovery,
        R.string.deleteMediaDiscoveryMessage,
        MediaDiscovery::class.java),
    goodDeeds(R.string.goodDeedsTitle,
        R.string.goodDeedsHint,
        R.string.noGoodDeedsMessage,
        R.string.addNewGoodDeed,
        R.string.editGoodDeed,
        R.string.deleteGoodDeedMessage,
        GoodDeed::class.java),
    dailySchedule(R.string.dailyScheduleTitle,
        R.string.dailyScheduleHint,
        R.string.noDailyScheduleMessage,
        R.string.addNewDailySchedule,
        R.string.editDailySchedule,
        R.string.deleteDailyScheduleMessage,
        DailySchedule::class.java),
    pleasantActions(R.string.pleasantActionsTitle,
        R.string.pleasantActionsHint,
        R.string.noPleasantActionMessage,
        R.string.addNewPleasantAction,
        R.string.editPleasantAction,
        R.string.deletePleasantActionMessage,
        PleasantAction::class.java),
    usefulActions(R.string.usefulActionsTitle,
        R.string.usefulActionsHint,
        R.string.noUsefulActionMessage,
        R.string.addNewUsefulAction,
        R.string.editUsefulAction,
        R.string.deleteUsefulActionMessage,
        UsefulAction::class.java),
    familyTasks(R.string.familyTasksTitle,
        R.string.familyTasksHint,
        R.string.noTasksMessage,
        R.string.addNewTask,
        R.string.editTask,
        R.string.deleteTaskMessage,
        FamilyTask::class.java),
    schoolTasks(R.string.schoolTasksTitle,
        R.string.schoolTasksHint,
        R.string.noTasksMessage,
        R.string.addNewTask,
        R.string.editTask,
        R.string.deleteTaskMessage,
        SchoolTask::class.java),
    churchTasks(R.string.churchTasksTitle,
        R.string.churchTasksHint,
        R.string.noTasksMessage,
        R.string.addNewTask,
        R.string.editTask,
        R.string.deleteTaskMessage,
        ChurchTask::class.java),
    finances(R.string.financesTitle,
        R.string.financesHint,
        R.string.noFinancesMessage,
        R.string.addNewFinance,
        R.string.editFinance,
        R.string.deleteFinanceMessage,
        Finance::class.java),
    borrows(R.string.borrowsTitle,
        R.string.borrowsHint,
        R.string.noBorrowsMessage,
        R.string.addNewBorrow,
        R.string.editBorrow,
        R.string.deleteBorrowMessage,
        Borrows::class.java),
    lends(R.string.lendsTitle,
        R.string.lendsHint,
        R.string.noLendsMessage,
        R.string.addNewLend,
        R.string.editLend,
        R.string.deleteLendMessage,
        Lends::class.java);
}

enum class PrayerType : LocalizedString {
    worship,
    confession,
    gratefulness,
    request,
    intercession,
    praise,
    gratitude
}

enum class FirestoreConstants : FirestoreCollection {
    categories,
    categoriesGroups,
    users,
    bibleBooks,
    favoriteCategories,
    history,
    reports,
    findings
}

enum class FirestoreFields : Labeled {
    order,
    date
}

