package ro.azs.kidsdevelopment.ui.firestoreEntry

object K {
    const val timestamp = "timestamp"
    const val bibleBook = "bibleBook"
    const val bibleBookChapter = "bibleBookChapter"
    const val discovery = "discovery"
    const val task = "task"
    const val prayerType = "prayerType"
    const val subject = "subject"
    const val description = "description"
    const val person = "person"
    const val reason = "reason"
    const val discoveryType = "discoveryType"
    const val bookAuthor = "bookAuthor"
    const val bookName = "bookName"
    const val sport = "sport"
    const val location = "location"
    const val findingType = "findingType"
    const val hobbyType = "hobbyType"
    const val typeDetails = "typeDetails"
    const val details = "details"
    const val deedType = "deedType"
    const val actionType = "actionType"
    const val action = "action"
    const val financeType = "financeType"
    const val amount = "amount"
    const val currency = "currency"
    const val height = "height"
    const val weight = "weight"
}
